=== hstrekowski/HyperText-HyperMedia-Project_1/ksiazki.dtd
<!ENTITY % dane_autora "(Imie, Nazwisko, Narodowosc)">
<!ENTITY % dane_wydawnicze "(Rok_Wydania_Polskiego, Wydawnictwo, ISBN)">

<!ELEMENT Hobby_Czytelnicze (Podsumowanie, Ulubione_Gatunki, Ksiazki)>

<!ATTLIST Hobby_Czytelnicze
    imie_autora CDATA #REQUIRED
    nazwisko_autora CDATA #REQUIRED
    indeks_autora CDATA #REQUIRED
    data_utworzenia CDATA #IMPLIED
    walidator CDATA "DTD"
    wersja_struktury (1.0 | 2.0) "1.0" 
>

<!ELEMENT Podsumowanie (Opis, Statystyki)>
<!ELEMENT Opis (Opis_Krotki | Opis_Rozwiniety)>
<!ELEMENT Opis_Krotki (#PCDATA)>
<!ELEMENT Opis_Rozwiniety (Tekst, Korzysci?)>
<!ELEMENT Tekst (#PCDATA)>
<!ELEMENT Korzysci (Punkt+)>
<!ELEMENT Punkt (#PCDATA)>

<!ELEMENT Statystyki (Statystyki_Roczne, Statystyki_Format)>
<!ELEMENT Statystyki_Roczne (Liczba_Przeczytanych, Liczba_Stron, Laczny_Czas_Czytania)>
<!ATTLIST Statystyki_Roczne rok CDATA #REQUIRED
>
<!ELEMENT Liczba_Przeczytanych (#PCDATA)>
<!ELEMENT Liczba_Stron (#PCDATA)>
<!ELEMENT Laczny_Czas_Czytania (#PCDATA)>

<!ATTLIST Liczba_Przeczytanych jednostka (sztuk | stron | godzin | książek) #REQUIRED
>
<!ATTLIST Liczba_Stron jednostka (sztuk | stron | godzin | książek) #REQUIRED
>
<!ATTLIST Laczny_Czas_Czytania jednostka (sztuk | stron | godzin | książek) #REQUIRED
>

<!ELEMENT Statystyki_Format (Format+)>
<!ELEMENT Format (#PCDATA)>
<!ATTLIST Format
    nazwa CDATA #REQUIRED
    jednostka CDATA #REQUIRED
>

<!ELEMENT Ulubione_Gatunki (Gatunek+)>
<!ELEMENT Gatunek (Nazwa, Opis_Gatunku, Przykladowi_Autorzy)>
<!ATTLIST Gatunek priorytet CDATA #REQUIRED
>
<!ELEMENT Nazwa (#PCDATA)>
<!ELEMENT Opis_Gatunku (#PCDATA)>
<!ELEMENT Przykladowi_Autorzy (Autor+)>

<!ELEMENT Autor (%dane_autora;)>
<!ATTLIST Autor rola (kluczowy | wazny | poboczny) #REQUIRED
>
<!ELEMENT Imie (#PCDATA)>
<!ELEMENT Nazwisko (#PCDATA)>
<!ELEMENT Narodowosc (#PCDATA)>

<!ELEMENT Ksiazki (Ksiazka+)>
<!ELEMENT Ksiazka (Tytul, Ostatnie_Trzy_Oceny?, Autor, Dane_Wydawnicze, Media)>
<!ATTLIST Ksiazka
    id CDATA #REQUIRED
    status (przeczytana | w_trakcie | do_przeczytania) #REQUIRED
    ocena CDATA #IMPLIED
>

<!ELEMENT Tytul (#PCDATA)>
<!ATTLIST Tytul jezyk CDATA #REQUIRED
>
<!ELEMENT Ostatnie_Trzy_Oceny (#PCDATA)>

<!ELEMENT Dane_Wydawnicze (%dane_wydawnicze;)>
<!ELEMENT Rok_Wydania_Polskiego (#PCDATA)>
<!ELEMENT Wydawnictwo (Nazwa_Skrocona, Siedziba_Glowna)>
<!ATTLIST Wydawnictwo nazwa_pelna CDATA #REQUIRED
>
<!ELEMENT Nazwa_Skrocona (#PCDATA)>
<!ELEMENT Siedziba_Glowna (Adres_Fizyczny)>
<!ELEMENT Adres_Fizyczny (Kraj, Miasto)>
<!ELEMENT Kraj (#PCDATA)>
<!ELEMENT Miasto (#PCDATA)>

<!ELEMENT ISBN (#PCDATA)>
<!ATTLIST ISBN typ (ISBN-10 | ISBN-13) #REQUIRED
>

<!ELEMENT Media (Okladka, Recenzja)>
<!ELEMENT Okladka (Zdjecie)>
<!ELEMENT Zdjecie EMPTY>
<!ATTLIST Zdjecie
    url CDATA #REQUIRED
    format (jpeg | png | webp) #REQUIRED
>
<!ELEMENT Recenzja (Link)>
<!ATTLIST Recenzja jezyk CDATA #REQUIRED
>
<!ELEMENT Link EMPTY>
<!ATTLIST Link
    typ (strona | video) "strona"
    url CDATA #REQUIRED>

=== hstrekowski/HyperText-HyperMedia-Project_1/ksiazki_kopia_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Hobby_Czytelnicze SYSTEM "ksiazki.dtd">
<Hobby_Czytelnicze
    imie_autora="Hubert"
    nazwisko_autora="Strękowski"
    indeks_autora="208381"
    walidator="DTD"
    wersja_struktury="1.0"
>

    <Podsumowanie>
        <Opis>
            <Opis_Rozwiniety>
                <Tekst>Czytanie to dla mnie forma relaksu i poszerzania wiedzy.</Tekst>
                <Korzysci>
                    <Punkt>Redukcja stresu</Punkt>
                    <Punkt>Rozwój słownictwa</Punkt>
                    <Punkt>Rozwój osobisty</Punkt>
                </Korzysci>
            </Opis_Rozwiniety>
        </Opis>
        <Statystyki>
            <Statystyki_Roczne rok="2024">
                <Liczba_Przeczytanych jednostka="sztuk">35</Liczba_Przeczytanych>
                <Liczba_Stron jednostka="stron">12540</Liczba_Stron>
                <Laczny_Czas_Czytania jednostka="godzin">285</Laczny_Czas_Czytania>
            </Statystyki_Roczne>
            <Statystyki_Format>
                <Format nazwa="Papier" jednostka="%">65</Format>
                <Format nazwa="E-book" jednostka="%">35</Format>
            </Statystyki_Format>
        </Statystyki>
    </Podsumowanie>

    <Ulubione_Gatunki>
        <Gatunek priorytet="1">
            <Nazwa>Fantastyka</Nazwa>
            <Opis_Gatunku> Światy magii, podróże w czasie i alternatywne rzeczywistości. </Opis_Gatunku>
            <Przykladowi_Autorzy>
                <Autor rola="kluczowy">
                    <Imie>Terry</Imie>
                    <Nazwisko>Pratchett</Nazwisko>
                    <Narodowosc>brytyjska</Narodowosc>
                </Autor>
                <Autor rola="wazny">
                    <Imie>Ursula K.</Imie>
                    <Nazwisko>Le Guin</Nazwisko>
                    <Narodowosc>amerykańska</Narodowosc>
                </Autor>
            </Przykladowi_Autorzy>
        </Gatunek>

        <Gatunek priorytet="2">
            <Nazwa>Kryminał</Nazwa>
            <Opis_Gatunku> Zagadki, śledztwa i nieoczekiwane zwroty akcji. Skupia się na logicznym
                rozwiązywaniu złożonych spraw kryminalnych. </Opis_Gatunku>
            <Przykladowi_Autorzy>
                <Autor rola="kluczowy">
                    <Imie>Agatha</Imie>
                    <Nazwisko>Christie</Nazwisko>
                    <Narodowosc>brytyjska</Narodowosc>
                </Autor>
                <Autor rola="poboczny">
                    <Imie>Raymond</Imie>
                    <Nazwisko>Chandler</Nazwisko>
                    <Narodowosc>amerykańska</Narodowosc>
                </Autor>
            </Przykladowi_Autorzy>
        </Gatunek>
    </Ulubione_Gatunki>


    <Ksiazki>
        <Ksiazka id="101" status="przeczytana" ocena="5">
            <Tytul jezyk="pl">Władca Pierścieni: Drużyna Pierścienia</Tytul>
            <Autor rola="kluczowy">
                <Imie>J.R.R.</Imie>
                <Nazwisko>Tolkien</Nazwisko>
                <Narodowosc>brytyjska</Narodowosc>
            </Autor>
            <Dane_Wydawnicze>
                <Rok_Wydania_Polskiego>1961</Rok_Wydania_Polskiego>
                <Wydawnictwo nazwa_pelna="Zysk i S-ka Wydawnictwo">
                    <Nazwa_Skrocona>Zysk i S-ka</Nazwa_Skrocona>
                    <Siedziba_Glowna>
                        <Adres_Fizyczny>
                            <Kraj>Polska</Kraj>
                            <Miasto>Poznań</Miasto>
                        </Adres_Fizyczny>
                    </Siedziba_Glowna>
                </Wydawnictwo>
                <ISBN typ="ISBN-13">978-8377852360</ISBN>
            </Dane_Wydawnicze>
            <Media>
                <Okladka>
                    <Zdjecie url="img/wladca_pierscieni.jpg" format="jpeg" />
                </Okladka>
                <Recenzja jezyk="pl">
                    <Link
                        url="https://nakanapie.pl/recenzje/wladca-pierscieni-druzyna-pierscienia-j-r-r-tol-wladca-pierscieni-t-1-druzyna-pierscienia" />
                </Recenzja>
            </Media>
        </Ksiazka>

        <Ksiazka id="102" status="przeczytana" ocena="4">
            <Tytul jezyk="en">Murder on the Orient Express</Tytul>
            <Autor rola="kluczowy">
                <Imie>Agatha</Imie>
                <Nazwisko>Christie</Nazwisko>
                <Narodowosc>brytyjska</Narodowosc>
            </Autor>
            <Dane_Wydawnicze>
                <Rok_Wydania_Polskiego>1963</Rok_Wydania_Polskiego>
                <Wydawnictwo nazwa_pelna="Wydawnictwo Dolnośląskie">
                    <Nazwa_Skrocona>WD</Nazwa_Skrocona>
                    <Siedziba_Glowna>
                        <Adres_Fizyczny>
                            <Kraj>Polska</Kraj>
                            <Miasto>Wrocław</Miasto>
                        </Adres_Fizyczny>
                    </Siedziba_Glowna>
                </Wydawnictwo>
                <ISBN typ="ISBN-13">978-8324578130</ISBN>
            </Dane_Wydawnicze>
            <Media>
                <Okladka>
                    <Zdjecie url="img/morderstwo_ekspres.jpg" format="jpeg" />
                </Okladka>
                <Recenzja jezyk="en">
                    <Link
                        url="https://warmdayswillnevercease.wordpress.com/2020/03/19/book-review-murder-on-the-orient-express-by-agatha-christie/" />
                </Recenzja>
            </Media>
        </Ksiazka>

        <Ksiazka id="103" status="w_trakcie" ocena="brak">
            <Tytul jezyk="pl">Sapiens: Od zwierząt do bogów</Tytul>
            <Ostatnie_Trzy_Oceny>4 5 5</Ostatnie_Trzy_Oceny>
            <Autor rola="kluczowy">
                <Imie>Yuval Noah</Imie>
                <Nazwisko>Harari</Nazwisko>
                <Narodowosc>izraelska</Narodowosc>
            </Autor>
            <Dane_Wydawnicze>
                <Rok_Wydania_Polskiego>2014</Rok_Wydania_Polskiego>
                <Wydawnictwo nazwa_pelna="Rebis - Dom Wydawniczy">
                    <Nazwa_Skrocona>Rebis</Nazwa_Skrocona>
                    <Siedziba_Glowna>
                        <Adres_Fizyczny>
                            <Kraj>Polska</Kraj>
                            <Miasto>Poznań</Miasto>
                        </Adres_Fizyczny>
                    </Siedziba_Glowna>
                </Wydawnictwo>
                <ISBN typ="ISBN-13">978-8380624891</ISBN>
            </Dane_Wydawnicze>
            <Media>
                <Okladka>
                    <Zdjecie url="img/sapiens.jpg" format="jpeg" />
                </Okladka>
                <Recenzja jezyk="pl">
                    <Link typ="video" url="https://www.youtube.com/watch?v=xoN9uowJ_pA" />
                </Recenzja>
            </Media>
        </Ksiazka>
    </Ksiazki>
</Hobby_Czytelnicze>
